Repository idaholab/MontePy, pull requests merged in 2024-08, with the labels that each got.

#471 Fixed edge case of bad typing in parser
  doc/source/changelog.rst
  montepy/input_parser/syntax_node.py
  tests/test_edge_cases.py
Labels: bugs

#472 Fix material to update compositions on export
  doc/source/changelog.rst
  montepy/data_inputs/isotope.py
  montepy/data_inputs/material.py
  montepy/input_parser/material_parser.py
  tests/test_material.py
Labels: bugs, code improvement

#474 Simplify isotope printing with __repr__
  doc/source/changelog.rst
  montepy/data_inputs/isotope.py
  tests/test_material.py
Labels: feature request

#481 Add robits
  README.md
  doc/source/conf.py
  doc/source/robots.txt
  pyproject.toml
Labels: documentation, enhancement, CI/CD, code improvement

#480 Fix bug with None type in syntax tree for get_trailing
  doc/source/changelog.rst
  montepy/input_parser/syntax_node.py
  tests/inputs/test_missing_mat_for_mt.imcnp
  tests/test_material.py
Labels: bugs

#479 Fix issue with floats in fill transform.
  doc/source/changelog.rst
  montepy/input_parser/cell_parser.py
  montepy/input_parser/parser_base.py
  tests/test_edge_cases.py
Labels: bugs, parsers are hard

#487 Fixed how metastable isomers are printed.
  doc/source/changelog.rst
  montepy/data_inputs/isotope.py
  tests/test_material.py
Labels: bugs

#495 Fixed sitemap URLs
  .github/scripts/check_sitemap.py
  .github/workflows/main.yml
  doc/source/conf.py
Labels: documentation, CI/CD

#493 Write to stream
  doc/source/changelog.rst
  doc/source/developing.rst
  doc/source/starting.rst
  montepy/__init__.py
  montepy/input_parser/input_file.py
  montepy/mcnp_problem.py
  tests/test_edge_cases.py
  tests/test_integration.py
  tests/test_mcnp_problem.py
Labels: code improvement, feature request

#488 Made method to auto insert new materials to data_inputs.
  doc/source/changelog.rst
  doc/source/developing.rst
  montepy/materials.py
  montepy/mcnp_problem.py
  montepy/numbered_object_collection.py
  tests/test_numbered_collection.py
Labels: enhancement, bugs, feature request

#484 Fixed bug with cell_modifiers being printed in comments.
  doc/source/changelog.rst
  montepy/cell.py
  montepy/data_inputs/cell_modifier.py
  montepy/input_parser/syntax_node.py
  montepy/mcnp_object.py
  montepy/numbered_object_collection.py
  tests/inputs/test_universe_data.imcnp
  tests/test_edge_cases.py
  tests/test_syntax_parsing.py
Labels: bugs, critical

#491 Bug fix for parentheses getting dropped from cell definitions.
  doc/source/changelog.rst
  montepy/geometry_operators.py
  montepy/input_parser/cell_parser.py
  montepy/surfaces/half_space.py
  montepy/utilities.py
  tests/inputs/test_paren_groups.imcnp
  tests/test_edge_cases.py
  tests/test_geometry.py
Labels: bugs, critical

#503 Update README for pending release
  README.md
Labels: documentation

#513 Add profiling and benckmarking
  .github/workflows/main.yml
  .gitignore
  benchmark/benchmark_big_model.py
  benchmark/big_model.imcnp
  prof/dump_results.py
  prof/profile_big_model.py
  pyproject.toml
Labels: CI/CD, performance 🐌

#518 Optimize Material Update Pointers
  .github/workflows/main.yml
  benchmark/benchmark_big_model.py
  doc/source/changelog.rst
  montepy/data_inputs/data_input.py
  montepy/data_inputs/material.py
  montepy/data_inputs/thermal_scattering.py
  montepy/mcnp_problem.py
  prof/dump_results.py
  prof/profile_big_model.py
  tests/test_material.py
Labels: code improvement, performance 🐌
