Repository idaholab/MontePy, pull requests merged in 2024-11, with the labels that each got.

#581 Adding more input context to all error messages.
  doc/source/changelog.rst
  montepy/errors.py
  montepy/input_parser/input_file.py
  montepy/mcnp_object.py
  montepy/universe.py
Labels: code improvement

#573 331 update readme
  CONTRIBUTING.md
  README.md
Labels: documentation, PyOpenSci / JOSS

#578 Run Examples in CI.
  .github/workflows/main.yml
  README.md
  demo/Pin_cell.ipynb
  doc/foo.imcnp
  doc/source/conf.py
  doc/source/developing.rst
  doc/source/foo.imcnp
  doc/source/migrations/migrate0_1.rst
  doc/source/starting.rst
  doc/source/tests
  doc/source/tricks.rst
  doc/source/utilities.rst
  doc/tests
  montepy/cell.py
  pyproject.toml
  tests/inputs/test.imcnp
  tests/test_cell_problem.py
  tests/test_integration.py
  tests/test_numbered_collection.py
  tests/test_syntax_parsing.py
Labels: bugs, CI/CD, PyOpenSci / JOSS

#592 Updated Pull Request Checklist
  .github/pull_request_template.md
Labels: documentation
