Repository idaholab/MontePy, pull requests merged in 2024-10, with the labels that each got.

#553 Make a stream readable.
  doc/source/changelog.rst
  montepy/input_parser/input_file.py
  montepy/input_parser/input_syntax_reader.py
  tests/test_integration.py
Labels: bugs, feature request

#561 Fixed bug that was comparing string to listNodes
  benchmark/benchmark_big_model.py
  doc/source/changelog.rst
  montepy/data_inputs/fill.py
  montepy/input_parser/syntax_node.py
  tests/inputs/test_universe.imcnp
  tests/test_integration.py
  tests/test_syntax_parsing.py
Labels: bugs

#562 Fixing bug when attempting to edit a cell geometry
  doc/source/changelog.rst
  montepy/surfaces/half_space.py
  montepy/surfaces/surface.py
  pyproject.toml
  tests/test_geom_integration.py
Labels: bugs

#548 Remove Python 3.8 support, and add python 3.13 and numpy 2.0 support
  .github/workflows/main.yml
  pyproject.toml
  tests/test_scripts.py
Labels: CI/CD, code improvement

#565 Switched to pydata theme.
  doc/source/_templates/placeholder
  doc/source/_templates/version.html
  doc/source/conf.py
  pyproject.toml
Labels: documentation, feature request

#568 Added hierarchy to MontePy changelog.
  doc/source/changelog.rst
Labels: documentation

#570 Documented what materials can't be parsed
  README.md
  doc/source/bugs.rst
  doc/source/starting.rst
  doc/source/users.rst
  montepy/data_inputs/material.py
Labels: documentation

#563 remove o(n^2) operation from NumberedObjectCollection
  .github/workflows/main.yml
  doc/source/changelog.rst
  montepy/cell.py
  montepy/data_inputs/material.py
  montepy/data_inputs/transform.py
  montepy/mcnp_problem.py
  montepy/numbered_mcnp_object.py
  montepy/numbered_object_collection.py
  montepy/surfaces/surface.py
  montepy/universe.py
  tests/test_integration.py
Labels: code improvement, feature request, performance 🐌

#468 Enable Pickling of Tallies
  doc/source/changelog.rst
  montepy/data_inputs/data_input.py
  montepy/input_parser/parser_base.py
  montepy/input_parser/tally_parser.py
  montepy/mcnp_object.py
  tests/inputs/test.imcnp
  tests/test_integration.py
  tests/test_syntax_parsing.py
Labels: bugs

#574 Fixed test_version to ensure it always has _version.py
  tests/test_version.py
Labels: bugs, CI/CD, code improvement, PyOpenSci / JOSS

#577 make version info more reliable for git archive
  .git_archival.txt
  .gitattributes
  .github/workflows/main.yml
Labels: CI/CD, code improvement
