Repository idaholab/MontePy, pull requests merged in 2024-07, with the labels that each got.

#423 Added discussion of why MCNP output files aren't supported to FAQ.
  .github/workflows/deploy.yml
  README.md
  doc/source/changelog.rst
  doc/source/faq.rst
  doc/source/scope.rst
Labels: documentation

#435 Link to MCNP discourse
  doc/source/index.rst
Labels: documentation

#438 Added inherit-members to all docs.
  doc/source/api/montepy.cell.rst
  doc/source/api/montepy.cells.rst
  doc/source/api/montepy.constants.rst
  doc/source/api/montepy.data_inputs.cell_modifier.rst
  doc/source/api/montepy.data_inputs.data_input.rst
  doc/source/api/montepy.data_inputs.data_parser.rst
  doc/source/api/montepy.data_inputs.element.rst
  doc/source/api/montepy.data_inputs.fill.rst
  doc/source/api/montepy.data_inputs.importance.rst
  doc/source/api/montepy.data_inputs.isotope.rst
  doc/source/api/montepy.data_inputs.lattice.rst
  doc/source/api/montepy.data_inputs.lattice_input.rst
  doc/source/api/montepy.data_inputs.material.rst
  doc/source/api/montepy.data_inputs.material_component.rst
  doc/source/api/montepy.data_inputs.mode.rst
  doc/source/api/montepy.data_inputs.rst
  doc/source/api/montepy.data_inputs.tally.rst
  doc/source/api/montepy.data_inputs.tally_multiplier.rst
  doc/source/api/montepy.data_inputs.thermal_scattering.rst
  doc/source/api/montepy.data_inputs.transform.rst
  doc/source/api/montepy.data_inputs.universe_input.rst
  doc/source/api/montepy.data_inputs.volume.rst
  doc/source/api/montepy.errors.rst
  doc/source/api/montepy.geometry_operators.rst
  doc/source/api/montepy.input_parser.block_type.rst
  doc/source/api/montepy.input_parser.cell_parser.rst
  doc/source/api/montepy.input_parser.data_parser.rst
  doc/source/api/montepy.input_parser.input_file.rst
  doc/source/api/montepy.input_parser.input_reader.rst
  doc/source/api/montepy.input_parser.input_syntax_reader.rst
  doc/source/api/montepy.input_parser.mcnp_input.rst
  doc/source/api/montepy.input_parser.parser_base.rst
  doc/source/api/montepy.input_parser.read_parser.rst
  doc/source/api/montepy.input_parser.rst
  doc/source/api/montepy.input_parser.shortcuts.rst
  doc/source/api/montepy.input_parser.surface_parser.rst
  doc/source/api/montepy.input_parser.syntax_node.rst
  doc/source/api/montepy.input_parser.tally_parser.rst
  doc/source/api/montepy.input_parser.thermal_parser.rst
  doc/source/api/montepy.input_parser.tokens.rst
  doc/source/api/montepy.materials.rst
  doc/source/api/montepy.mcnp_object.rst
  doc/source/api/montepy.mcnp_problem.rst
  doc/source/api/montepy.numbered_mcnp_object.rst
  doc/source/api/montepy.numbered_object_collection.rst
  doc/source/api/montepy.particle.rst
  doc/source/api/montepy.surface_collection.rst
  doc/source/api/montepy.surfaces.axis_plane.rst
  doc/source/api/montepy.surfaces.cylinder_on_axis.rst
  doc/source/api/montepy.surfaces.cylinder_par_axis.rst
  doc/source/api/montepy.surfaces.general_plane.rst
  doc/source/api/montepy.surfaces.half_space.rst
  doc/source/api/montepy.surfaces.rst
  doc/source/api/montepy.surfaces.surface.rst
  doc/source/api/montepy.surfaces.surface_builder.rst
  doc/source/api/montepy.surfaces.surface_type.rst
  doc/source/api/montepy.transforms.rst
  doc/source/api/montepy.universe.rst
  doc/source/api/montepy.universes.rst
  doc/source/api/montepy.utilities.rst
Labels: documentation

#443 Implemented overwrite guardrails thanks to @tjlaboss.
  doc/source/changelog.rst
  doc/source/starting.rst
  montepy/input_parser/input_file.py
  montepy/mcnp_problem.py
  tests/test_input_file.py
  tests/test_integration.py
Labels: code improvement

#444 Updated dependency to sphinx 7.4.0, and enabled linkcheck testing.
  .github/workflows/deploy.yml
  .github/workflows/main.yml
  pyproject.toml
Labels: documentation, CI/CD

#431 Fixed Parser bug with Source Definition
  doc/source/api/montepy.data_inputs.rst
  doc/source/api/montepy.data_inputs.tally.rst
  doc/source/api/montepy.data_inputs.tally_multiplier.rst
  doc/source/changelog.rst
  doc/source/developing.rst
  montepy/data_inputs/cell_modifier.py
  montepy/data_inputs/data_input.py
  montepy/data_inputs/data_parser.py
  montepy/data_inputs/tally.py
  montepy/data_inputs/tally_multiplier.py
  montepy/data_inputs/tally_segment.py
  montepy/input_parser/__init__.py
  montepy/input_parser/data_parser.py
  montepy/input_parser/parser_base.py
  montepy/input_parser/syntax_node.py
  montepy/input_parser/tally_parser.py
  montepy/input_parser/tally_seg_parser.py
  montepy/input_parser/tokens.py
  pyproject.toml
  tests/test_integration.py
  tests/test_source.py
  tests/test_syntax_parsing.py
Labels: bugs, critical, parsers are hard

#440 Implementing feedback from PyOpenSci peer reviews.
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  doc/source/changelog.rst
  doc/source/index.rst
  doc/source/starting.rst
Labels: documentation, code improvement

#451 Fix parser error with implicit intersection
  doc/source/changelog.rst
  montepy/input_parser/cell_parser.py
  tests/test_cell_problem.py
  tests/test_edge_cases.py
Labels: bugs, critical, parsers are hard

#459 Solved error with trailing dollar-sign comments moving on export
  doc/source/changelog.rst
  montepy/input_parser/syntax_node.py
  tests/inputs/test.imcnp
  tests/test_syntax_parsing.py
Labels: bugs
