Repository idaholab/MontePy, pull requests merged in 2024-12, with the labels that each got.

#600 Implement RTD support
  .github/scripts/check_sitemap.py
  .github/workflows/main.yml
  .readthedocs.yaml
  doc/source/_templates/project.html
  doc/source/conf.py
  doc/source/dev_tree.rst
  doc/source/developing.rst
  doc/source/index.rst
  doc/source/robots.txt
  doc/source/starting.rst
  pyproject.toml
Labels: documentation, CI/CD

#598 Fix bug with how new material components are exported.
  .github/pull_request_template.md
  doc/source/changelog.rst
  montepy/data_inputs/material.py
  pyproject.toml
  tests/test_material.py
Labels: bugs, critical

#610 Relax sly dependency to include sly 0.4
  .github/workflows/main.yml
  pyproject.toml
Labels: CI/CD, code improvement

#614 Release 0.5.3.post1
  .github/workflows/main.yml
  pyproject.toml
Labels: CI/CD, code improvement

#616 Delete GH pages deploy process.
  .github/workflows/deploy.yml
  CNAME
  README.md
Labels: CI/CD

#618 Added conda forge badge.
  README.md
  doc/source/developing.rst
Labels: documentation

#624 Added RTD action.
  .github/workflows/main.yml
Labels: documentation, CI/CD

#625 Remove '"""' from PR template
  .github/pull_request_template.md
Labels: CI/CD, low priority

#627 Rtd action update
  .github/workflows/main.yml
  .github/workflows/rtd_link.yml
Labels: CI/CD
