Repository idaholab/MontePy, pull requests merged in 2024-09, with the labels that each got.

#538 Fixed bug double adding materials.
  doc/source/changelog.rst
  montepy/numbered_object_collection.py
  tests/test_numbered_collection.py
Labels: bugs

#528 Marked material_components for deprecation.
  doc/source/changelog.rst
  doc/source/migrations/migrate0_1.rst
  doc/source/users.rst
  montepy/data_inputs/isotope.py
  montepy/data_inputs/material.py
  montepy/data_inputs/material_component.py
  tests/test_material.py
Labels: documentation, code improvement

#541 ASCII Snake
  graphics/ascii.txt
Labels: low priority

#520 Fix issue with shortcut recompression
  doc/source/changelog.rst
  montepy/cell.py
  montepy/data_inputs/importance.py
  montepy/data_inputs/universe_input.py
  montepy/data_inputs/volume.py
  montepy/input_parser/cell_parser.py
  montepy/input_parser/input_reader.py
  montepy/input_parser/material_parser.py
  montepy/input_parser/syntax_node.py
  montepy/mcnp_problem.py
  montepy/surfaces/cylinder_on_axis.py
  tests/inputs/test_complement_edge.imcnp
  tests/inputs/test_importance.imcnp
  tests/inputs/test_trail_comment_edge.imcnp
  tests/test_edge_cases.py
  tests/test_integration.py
  tests/test_syntax_parsing.py
Labels: bugs, CI/CD, code improvement, critical

#546 Add pyproject link to changelog
  pyproject.toml
Labels: documentation

#554 Made multi-format multi-resolution favicons.
  .gitignore
  doc/source/_static/monty-192.png
  doc/source/_static/monty-32.ico
  doc/source/_static/monty-32.png
  doc/source/_static/monty.svg
  doc/source/_static/placeholder
  doc/source/conf.py
  graphics/monty-192.png
  graphics/monty-32.ico
  graphics/monty-32.png
  pyproject.toml
Labels: documentation
