Repository idaholab/MontePy, pull requests merged in 2025-03, with the labels that each got.

#673 Fixed parsing error with sigma baryons
  doc/source/changelog.rst
  montepy/input_parser/parser_base.py
  montepy/input_parser/syntax_node.py
  montepy/input_parser/tokens.py
  tests/inputs/test_complement_edge.imcnp
Labels: bugs, parsers are hard

#663 Allow strictly finding material components
  doc/source/changelog.rst
  doc/source/starting.rst
  montepy/data_inputs/material.py
  montepy/materials.py
  tests/test_material.py
  tests/test_numbered_collection.py
Labels: alpha testing, feature request

#680 Allow any Real type for floating point numbers and any Integral type for integer numbers during type enforcement
  doc/source/changelog.rst
  montepy/cell.py
  montepy/cells.py
  montepy/data_inputs/element.py
  montepy/data_inputs/material.py
  montepy/data_inputs/nuclide.py
  montepy/input_parser/syntax_node.py
  montepy/materials.py
  montepy/numbered_mcnp_object.py
  montepy/numbered_object_collection.py
  montepy/surfaces/cylinder_par_axis.py
  montepy/surfaces/half_space.py
  montepy/surfaces/surface.py
  montepy/universe.py
  tests/test_numbers.py
Labels: alpha testing, code improvement

#647 Address review comments from PyOpenSci
  README.md
  doc/source/starting.rst
  pyproject.toml
Labels: documentation, PyOpenSci / JOSS

#693 Documented naming conventions.
  doc/source/dev_standards.rst
Labels: documentation

#668 Implemented clear for material
  doc/source/changelog.rst
  montepy/cell.py
  montepy/data_inputs/material.py
  montepy/errors.py
  montepy/input_parser/input_syntax_reader.py
  montepy/input_parser/material_parser.py
  montepy/input_parser/mcnp_input.py
  montepy/input_parser/parser_base.py
  montepy/input_parser/syntax_node.py
  montepy/mcnp_object.py
  montepy/mcnp_problem.py
  tests/inputs/pin_cell.imcnp
  tests/inputs/test.imcnp
  tests/inputs/test_complement_edge.imcnp
  tests/test_integration.py
  tests/test_material.py
  tests/test_syntax_parsing.py
Labels: alpha testing, bugs, code improvement, feature request, parsers are hard

#701 Fixed bug where lat, fill, universe not always exporting.
  doc/source/changelog.rst
  doc/source/starting.rst
  montepy/_cell_data_control.py
  montepy/cell.py
  montepy/data_inputs/lattice_input.py
  montepy/mcnp_problem.py
  tests/inputs/test_interp_edge.imcnp
  tests/test_cell_problem.py
  tests/test_integration.py
  tests/test_universe_integration.py
Labels: bugs

#649 Add munkm feedback to JOSS paper
  inst/paper.bib
  inst/paper.md
Labels: documentation, PyOpenSci / JOSS

#707 705 bug with no default universe
  doc/source/changelog.rst
  montepy/data_inputs/universe_input.py
  tests/test_universe_integration.py
Labels: alpha testing, bugs

#710 Fixed surfaces cant be unset from is reflecting
  doc/source/changelog.rst
  montepy/input_parser/syntax_node.py
  montepy/mcnp_object.py
  montepy/surfaces/surface.py
  tests/test_surfaces.py
Labels: alpha testing, bugs

#712 Added PyOpenSci and Zenodo badges.
  README.md
Labels: documentation, PyOpenSci / JOSS

#681 Add failing test case for issue #549 (empty Importance object print)
  .gitignore
  AUTHORS
  doc/source/changelog.rst
  montepy/data_inputs/importance.py
  pyproject.toml
  tests/test_importance.py
Labels: bugs, CI/CD, code improvement

#717 Allow setting multi-universe fills
  doc/source/changelog.rst
  montepy/data_inputs/fill.py
  tests/test_universe.py
Labels: alpha testing, bugs

#725 Updated templates to use type, and be more legible.
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation
