Repository idaholab/MontePy, pull requests merged in 2025-07, with the labels that each got.

#772 Added FQ input to test suite.
  tests/inputs/test_importance.imcnp
Labels: code improvement

#773 Manage GH actions security
  .github/dependabot.yml
  .github/workflows/deploy.yml
  .github/workflows/main.yml
Labels: CI/CD, code improvement

#747 Made making surfaces from scratch possible.
  doc/source/changelog.rst
  doc/source/developing.rst
  montepy/input_parser/syntax_node.py
  montepy/numbered_mcnp_object.py
  montepy/numbered_object_collection.py
  montepy/surfaces/axis_plane.py
  montepy/surfaces/cylinder_on_axis.py
  montepy/surfaces/cylinder_par_axis.py
  montepy/surfaces/surface.py
  tests/test_numbered_collection.py
  tests/test_surfaces.py
Labels: bugs

#775 Added some top level use case info to help with keywords for SEO.
  README.md
  doc/source/index.rst
  doc/source/robots.txt
Labels: documentation

#778 Refactor montepy.errors -> montepy.exceptions
  doc/source/api/modules.rst
  doc/source/api/montepy.errors.rst
  doc/source/api/montepy.exceptions.rst
  doc/source/changelog.rst
  montepy/__init__.py
  montepy/cell.py
  montepy/cells.py
  montepy/constants.py
  montepy/data_inputs/cell_modifier.py
  montepy/data_inputs/data_input.py
  montepy/data_inputs/element.py
  montepy/data_inputs/fill.py
  montepy/data_inputs/importance.py
  montepy/data_inputs/lattice_input.py
  montepy/data_inputs/material.py
  montepy/data_inputs/thermal_scattering.py
  montepy/data_inputs/transform.py
  montepy/data_inputs/universe_input.py
  montepy/data_inputs/volume.py
  montepy/errors.py
  montepy/exceptions.py
  montepy/input_parser/cell_parser.py
  montepy/input_parser/data_parser.py
  montepy/input_parser/input_syntax_reader.py
  montepy/input_parser/mcnp_input.py
  montepy/input_parser/syntax_node.py
  montepy/mcnp_object.py
  montepy/mcnp_problem.py
  montepy/numbered_object_collection.py
  montepy/surfaces/axis_plane.py
  montepy/surfaces/cylinder_on_axis.py
  montepy/surfaces/cylinder_par_axis.py
  montepy/surfaces/general_plane.py
  montepy/surfaces/half_space.py
  montepy/surfaces/surface.py
  tests/test_cell_problem.py
  tests/test_data_inputs.py
  tests/test_edge_cases.py
  tests/test_errors.py
  tests/test_geom_integration.py
  tests/test_importance.py
  tests/test_integration.py
  tests/test_main.py
  tests/test_material.py
  tests/test_mode.py
  tests/test_nuclide.py
  tests/test_numbered_collection.py
  tests/test_source.py
  tests/test_surfaces.py
  tests/test_syntax_parsing.py
  tests/test_tally.py
  tests/test_transform.py
  tests/test_universe.py
Labels: code improvement, low priority

#781 adopt spec 0
  .github/workflows/main.yml
  README.md
  doc/source/changelog.rst
  doc/source/dev_standards.rst
  pyproject.toml
Labels: CI/CD, code improvement, dependencies, github_actions
