Repository idaholab/MontePy, pull requests merged in 2025-05, with the labels that each got.

#749 Feature/361 find cells generator
  doc/source/changelog.rst
  doc/source/conf.py
  doc/source/starting.rst
  montepy/universe.py
  tests/test_universe.py
Labels: code improvement, feature request

#758 Added JOSS to home page.
  doc/source/index.rst
Labels: documentation

#757 Fixed bug with bad rounding for floating point value nodes on export
  .github/pull_request_template.md
  doc/source/changelog.rst
  montepy/input_parser/syntax_node.py
  tests/test_syntax_parsing.py
Labels: bugs, critical

#763 General plane warning if more than 9 constants.
  AUTHORS
  doc/source/_test_for_missing_docs.py
  doc/source/changelog.rst
  montepy/errors.py
  montepy/surfaces/general_plane.py
  pyproject.toml
  tests/test_surfaces.py
Labels: code improvement, feature request

#760 Fixed detection of vertical mode in cell defintions
  .github/pull_request_template.md
  doc/source/changelog.rst
  montepy/cell.py
  montepy/errors.py
  montepy/input_parser/input_syntax_reader.py
  montepy/mcnp_object.py
  tests/inputs/test_broken_mat_link.imcnp
Labels: bugs, parsers are hard

#750 Deploying workshop demos
  .github/workflows/main.yml
  README.md
  demo/0_IntroToMontePy.ipynb
  demo/1_PinCellCorrection_inter.ipynb
  demo/2_BuildAssembly_inter.ipynb
  demo/3_AddingGuideTubes_inter.ipynb
  demo/4_AxialDiscretize_inter.ipynb
  demo/5_AdapterSegue.ipynb
  demo/Pin_cell.ipynb
  demo/_config.py
  demo/answers/1_PinCellCorrection.ipynb
  demo/answers/2_BuildAssembly.ipynb
  demo/answers/3_AddingGuideTubes.ipynb
  demo/answers/4_AxialDiscretize.ipynb
  demo/answers/_config.py
  demo/answers/figs
  demo/answers/models
  demo/figs/all_pins.png
  demo/figs/guide_pin.png
  demo/figs/instrument_tube.png
  demo/figs/montepy_qr.png
  demo/figs/pin_cell.png
  demo/figs/w17x17_axial.png
  demo/figs/w17x17_guide.png
  demo/figs/w17x17_instrument.png
  demo/figs/w17x17_layout.png
  demo/figs/w17x17_layout_labeled.png
  demo/figs/w17x17_plot.png
  demo/figs/w_17_17_axial_xy.png
  demo/jupyter_conda_env.txt
  demo/models/oops_all_pins_ans.imcnp
  demo/models/pin_cell.imcnp
  demo/models/pin_cell_corrected_ans.imcnp
  demo/models/w17_17_full_height_ans.imcnp
  demo/models/w17_17_k_inf_ans.imcnp
  demo/pin_cell.imcnp
  demo/rise.css
  doc/source/changelog.rst
  doc/source/starting.rst
  pyproject.toml
  tests/test_universe_integration.py
Labels: documentation
